### ISSUE TITLE
wrong url while trying to authenticate via twitter

### ISSUE THREAD

**Issue by omansour** [afup/haphpy-birthday#11]
from http://haphpy-birthday.dev/app_dev.php/en/ (local install) when clic to github authentication I am redirected to http://haphpy-birthday.woecifaun.net/login/

![mozilla_firefox](https://cloud.githubusercontent.com/assets/1131098/8391833/73318ca4-1cd1-11e5-9abc-7a618f9b6761.jpg)

**Comment by omansour** [comment]
never mind.I was on the wrong branch

**Comment by woecifaun** [comment]
You were not wrong. The documentation was incomplete.

You need to register your local app in GitHub to allow authentication trough it.

I updated the documentation. I splitted it and add a special page on how to set up GitHub for authentication:
[Activate the application at github.com for OAuth](https://github.com/afup/haphpy-birthday/blob/master/docs/register-github.md)

It's now part of the requirements in the install section.
