### ISSUE TITLE
Allow user to delete its contribution

### ISSUE THREAD

**Issue by woecifaun** [afup/haphpy-birthday#40]
If  someone is authenticated and has submitted a contribution already, replace the form by a button to delete the contribution.

**Comment by agallou** [comment]
what did you have in mind, something like this ? 

![capture d ecran 2015-07-11 a 09 09 49](https://cloud.githubusercontent.com/assets/320372/8632860/b1b591ec-27ac-11e5-802d-91aadd0e30c9.png)

**Comment by woecifaun** [comment]
Yes exactly.

I also created the PR https://github.com/afup/haphpy-birthday/issues/46 to display the uploaded media to its owner.
