### ISSUE TITLE
Add a moderation system

### ISSUE THREAD

**Issue by woecifaun** [afup/haphpy-birthday#51]
> :warning: Starting to work on this issue? please indicate it in a comment below.

The first contribution on the demo website seemed to be a hoax.

It should be good to have a kind of a moderation admin for specific users.

As well, a message saying to the user its contribution will be moderated or has been rejected/accepted.

**Comment by agallou** [comment]
Does a backend with sonata and a flag in the database to indicate if the contribution has been rejected will be ok ?

**Comment by woecifaun** [comment]
I just thought of a list of all contributions (public and anonymous) accessible only by admins.

Each line with name, auth provider, moderated or not, and for the media a preview either a modal  on click or inline.

Not sure even for 500 contributions we need pagination but why not if it's easy.

I never used sonata and if it's not overkill, it's good for me.
