### ISSUE TITLE
Set up Sass

### ISSUE THREAD

**Issue by woecifaun** [afup/haphpy-birthday#58]
> :warning: Starting to work on this issue? please indicate it in a comment below.

Set up Sass

**Comment by agallou** [comment]
is it ok for you to use the same configuration as the barometre project ? https://github.com/afup/barometre

**Comment by woecifaun** [comment]
I can't remember what's on the _barometre_. I think it's ok.

Right now, there is just the CSS directly in the assets directory. I wanted to split it up a little. I think elaostrap has sass scripts too.

And finally, there could be javascript too (in fact there is for elaostrap).

**Comment by mikaelkael** [comment]
Yes.  It's perfect like with baromètre.

**Comment by agallou** [comment]
Je commence à mettre en place sass.

**Comment by woecifaun** [comment]
:smile:  Thanks for telling.
