### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by woecifaun** [afup/haphpy-birthday#8]
- [x] Add **translated** `description` ~~and `keyword`~~ meta elements.
- [ ] Handle robots.txt.

**Comment by agallou** [comment]
no need to add a keyword meta : https://support.google.com/webmasters/answer/79812 (http://googlewebmastercentral.blogspot.fr/2009/09/google-does-not-use-keywords-meta-tag.html)

**Comment by woecifaun** [comment]
After a quick search, it seems we don't need robots.txt as we want crawlers to look every pages which is the default behavior.

I close the issue.
